name: Build and publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-n-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_os: [windows]
        go-arch: [amd64]

    steps:
      - name: Checkout workspace
        uses: actions/checkout@master
        with:
          repository: lgc2333/BetterNCM-Workspace
          submodules: true

      - name: Get package folder name
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          FOLDER_NAME=$(echo "${REPO_NAME}" | sed 's/^BetterNCM-//')
          echo "FOLDER_NAME=${FOLDER_NAME}"
          echo "FOLDER_NAME=${FOLDER_NAME}" >> $GITHUB_ENV

      - name: Update current package submodule
        run: |-
          git switch ${{ github.ref_name }}
          git pull

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Corepack
        run: |-
          npm install -g corepack
          corepack enable

      - name: Install Node dependencies
        run: yarn

      - name: Install Go dependencies
        run: |-
          cd packages/${FOLDER_NAME}/backend-server
          go get .

      - name: Build
        env:
          GOOS: ${{ matrix.go_os }}
          GOARCH: ${{ matrix.go-arch }}
        run: |-
          cd packages/${FOLDER_NAME}
          yarn build

      - name: Deploy
        uses: lgc2333/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: dist
          FOLDER: packages/${{ env.FOLDER_NAME }}/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'upload dist [skip-ci]'
          SQUASH_HISTORY: true
